### ISSUE TITLE
Odd return value for GetByteLength on Boolean StackItem

### ISSUE THREAD

**Issue by ixje** [neo-project/neo-vm#129]
A StackItem of type Boolean with a `false` state returns 0 when calling `GetByteLength()` on it. This seems counter intuitive as `false` is still a value and takes up space in memory. Should the Boolean StackItem type not always return a length of 1? 

My rationale is; I expect `GetByteArray()` to return 1 byte set to `0` for `false` and set to `1` for `true`, this would then result in `GetByteLength()` to always be `1`. Neither of these assumptions is true (meaning; `GetByteArray()` on a Boolean with a `false` state, returns an empty bytearray). If this is intentional, why is it like that?

**Comment by ixje** [comment]
@shargon what are your thoughts on this? The above issue got triggered by a recent test you added so I'm assuming you'll have an idea about it :)
https://github.com/neo-project/neo-vm/blob/a3f94445ff8de4fdea9388652f5dff9243d2c13b/tests/neo-vm.Tests/Tests/OpCodes/Splice/SIZE.json#L173-L174

**Comment by ixje** [comment]
To elaborate; this is my expected behaviour but in a normal language like C#
```C#
            bool boolValue = false;

            Console.WriteLine("Bool value: " + boolValue.ToString());

            byte[] bytes = BitConverter.GetBytes(boolValue);

            Console.WriteLine("Byte array value: {0}", BitConverter.ToString(bytes));
            Console.WriteLine("bytes len {0}", bytes.Length);
```
returns
```
Bool value: False
Byte array value: 00
bytes len 1
```

**Comment by shargon** [comment]
I just know that is the expected behaviour inside the virtual machine ... it could be strange, but `new byte[]{ 0x00}` is `false` too inside the virtual machine.

**Comment by ixje** [comment]
I understand that this is how the VM has been working up to now. I raise the question if that is actually what we want. I think 
 https://github.com/neo-project/neo-vm/blob/a3f94445ff8de4fdea9388652f5dff9243d2c13b/src/neo-vm/Types/Boolean.cs#L9
should be
```C#
private static readonly byte[] FALSE = { 0x00 }; 
```

because then this
```C#
            StackItem true_item = new Neo.VM.Types.Boolean(true);
            StackItem false_item = new Neo.VM.Types.Boolean(false);
            Console.WriteLine(true_item.GetByteLength());
            Console.WriteLine(false_item.GetByteLength());
```
would not output
```
1
0
```
but
```
1
1
```
which is inline with how C#'s build in `BitConverter` works and how many other languages convert.

Let's ask for more opinions: @igormcoelho @vncoelho

**Comment by igormcoelho** [comment]
This is an interesting question @ixje, let me explain. The Boolean stackitem needs a definition for true/false, and personally I don't know which is the oldest version that was adopted, but like shargon said, we will need to preserve this on Neo 2.X, but we could improve for Neo 3. 
When you code a smart contract that returns any int zero (like `int i = 0;`), compiler will issue a `PUSH0`. However, PUSH0 is not actually pushing the value zero to the stack, but an empty array. This is fine, because on BigInteger format, all left-zeros can be removed without issue until you get a byte with top bit set to one (the zero before this you cannot remove, otherwise you change sign). So, an empty array is in fact a value false (as usual, integer 0). But its byte size would indeed be zero, because it's an empty bytearray (obviously every language would have somewhere at least size control that would make it not perfectly zero, but officially the byte array is zero length).
So: `[ ]` is false. `[ 1 ]` is true. `[ 2 ]` should be true as well, and `[ -1 ]` too. One thing I don't know, is that if `[ 0 ]` is false too. Is it? I was hoping in fact that `[ 0 0 0 0 0 ]` is also false. Is it? So, we could indeed improve this check, as long as it does not break any past compatibility.
