### ISSUE TITLE
Redesign PUSH opcodes

### ISSUE THREAD

**Issue by erikzhang** [neo-project/neo-vm#235]
```c#
public enum OpCode : byte
{
    //Push integers
    PUSHINT8 = 0x00,
    PUSHINT16 = 0x01,
    PUSHINT32 = 0x02,
    PUSHINT64 = 0x03,
    PUSHINT128 = 0x04,
    PUSHINT256 = 0x05,
    //0x06 is reserved for PUSHINT512
    //0x07 is reserved for PUSHINT1K
    //0x08 is reserved for PUSHINT2K
    //0x09 is reserved for PUSHINT4K
    //0x0A is reserved for PUSHINT8K

    //Push null
    PUSHNULL = 0x0B,

    //Push byte arrays
    PUSHDATA1 = 0x0C,
    PUSHDATA2 = 0x0D,
    PUSHDATA4 = 0x0E,

    //Push small integers
    PUSHM1 = 0x0F,
    PUSH0 = 0x10,
    PUSH1 = 0x11,
    PUSH2 = 0x12,
    PUSH3 = 0x13,
    PUSH4 = 0x14,
    PUSH5 = 0x15,
    PUSH6 = 0x16,
    PUSH7 = 0x17,
    PUSH8 = 0x18,
    PUSH9 = 0x19,
    PUSH10 = 0x1A,
    PUSH11 = 0x1B,
    PUSH12 = 0x1C,
    PUSH13 = 0x1D,
    PUSH14 = 0x1E,
    PUSH15 = 0x1F,
    PUSH16 = 0x20,
}
```

**Comment by erikzhang** [comment]
After the reference tracing is merged, I will work on this.

**Comment by lightszero** [comment]
agree,and if you agree to delete more pushs is better.
most of this pushs,is design for save only 1 byte.

**Comment by erikzhang** [comment]
@lightszero Which opcodes do you think can be deleted?

**Comment by igormcoelho** [comment]
Interesting Erik, but no hope to follow a PUSHVARDATA instead of PUSHDATA 1 2 4 ? I think it would be easier and more compatible to Neo serialization pattern.

**Comment by erikzhang** [comment]
`PUSHVARDATA` needs 4 reads to load into the data.

**Comment by igormcoelho** [comment]
4 reads only for huge data... when dealing with such data, four reads is not the biggest issue.
Erik, pushint32 follows which endian convention? Is it equivalent to pushbytes32, and convert to little endian?
If so, how can I push 32 zeroes on stack?

**Comment by erikzhang** [comment]
There is a new opcode `NEWBUFFER = 0x84` in #238.

**Comment by roman-khimov** [comment]
I can just ask the same question as in #212, what's the basis of this refactoring other than someone's gut feeling? It's not that it's bad, it's nice in its own way, but hey, we have another visually appealing proposal from @igormcoelho in #212, how do we compare the two now? I think we can only do that by using some real data from real contracts (and other scripts) that we have in mainnet and testnet. Figuring out what's used most, trying to estimate how things would change if we're to touch something, going that route rather than just rolling out yet another opcode set.

As for the opcodes, I think I'm missing `PUSHBYTES33` and `PUSHBYTES20` in this set. The first one is definitely used a lot (every verification script has it) and the second one is also quite frequent in invocation scripts. Using `PUSHDATA1` for these is 2,9% and 4,8% overhead respectively. `PUSHBYTES64` can also be considered for obvious reasons, although it's a bit less of concern with its 1,5% overhead.

**Comment by erikzhang** [comment]
Indeed, `PUSHBYTES33` is currently used a lot. However, it is unlikely that we will reserve a `PUSHBYTES33` opcode in NeoVM, which will seem strange. And PUSHBYTES33 is basically used to push the public key. The length of the public key is not only 33 bytes. In the future, we may support other signature algorithms. So the 2.9% overhead is currently acceptable.

In addition, we can try to optimize it from the NEO side. We can support multiple types of `Witness` structures. For example, the `ScriptHash` structure compatible with the present, and Bitcoin's `PublicKeyHash` structure.

**Comment by roman-khimov** [comment]
> If we support PublicKeyHash witness, we can verify the transactions without runing NeoVM.

That would be interesting, I think. Spawning VM to run three opcodes in it for signature check is quite expensive.

**Comment by shargon** [comment]
Definitely a very good idea

**Comment by igormcoelho** [comment]
I agree, we have two views here... my proposal aimed to make neovm push system very similar to neo serialization standard.. from this perspective I'd support push0-127 and pushvarbytes. Looks very good to me.
from other perspective, we can support few opcodes for push system, accept overheads and make it quite.minimal,looks promising too. For me, both ways are good, so I also support this one.
