### ISSUE TITLE
Redesign flow-control opcodes

### ISSUE THREAD

**Issue by erikzhang** [neo-project/neo-vm#236]
```c#
public enum OpCode : byte
{
    //NOP
    NOP = 0x21,

    //Jumps
    JMP = 0x22,
    JMP_L = 0x23,
    JMPIF = 0x24,
    JMPIF_L = 0x25,
    JMPIFNOT = 0x26,
    JMPIFNOT_L = 0x27,
    JMPEQ = 0x28,
    JMPEQ_L = 0x29,
    JMPNE = 0x2A,
    JMPNE_L = 0x2B,
    JMPGT = 0x2C,
    JMPGT_L = 0x2D,
    JMPGE = 0x2E,
    JMPGE_L = 0x2F,
    JMPLT = 0x30,
    JMPLT_L = 0x31,
    JMPLE = 0x32,
    JMPLE_L = 0x33,

    //Calls
    CALL = 0x34,
    CALL_L = 0x35,
    //Reserved 0x36

    //Exceptions
    THROW = 0x37,
    THROWIF = 0x38,
    THROWIFNOT = 0x39,
    //Reserved 0x3A
    TRY = 0x3B,
    TRY_L = 0x3C,
    ENDT = 0x3D, //End try
    ENDC = 0x3E, //End catch
    ENDF = 0x3F, //End finally

    //Others
    RET = 0x40,
    SYSCALL = 0x41,
}
```

A `TRY-CATCH` design: #192

**Comment by shargon** [comment]
- What means the `_L`?
- We need a `TRY_FINISH` , we will accept multiple `catch` ?

**Comment by erikzhang** [comment]
> What means the _L?

`_L` is the long jump versions. The opcodes without `_L` suffix accept `int8` as the operand. The opcodes with `_L` suffix accept `int32` as the operand.

**Comment by erikzhang** [comment]
> We need a TRY_FINISH , we will accept multiple catch ?

It is named as `ENDTRY = 0x4C`.

**Comment by shargon** [comment]
But if we only accept SmartContracts of 64k, does we need long jumps?

**Comment by erikzhang** [comment]
We may accept larger scripts in the future. So we need to reserve for it.

**Comment by igormcoelho** [comment]
Interesting approach Erik... do you think usability will be high for all jump types? And could int8 jumps suffice for most common cases? Whats the general feeling?

**Comment by roman-khimov** [comment]
I'm still a little skeptical about `_L` jumps, but a very quick check on two random smart contracts has shown that using this `JMP` encoding scheme (with an opcode for one byte offset and an opcode for four bytes offset) rather than plain two bytes offset would reduce the code occupied by  jumps in these contracts by 5,4% and 14% (and jumps occupy 6% and and 4,9% of the overall script size in these cases). So it might be a good change, but that can be defeated if we're to check a larger corpus of code, who knows.

The other change that I see here is comparison embedding, which seems like a nice idea that could save quite some code, but my two test contracts (from mainnet) disagree with it for some reason. In one of them out of 40 `JMPIF`/`JMPIFNOT` instructions 37 are preceeded by `PICKITEM`, 2 by `LT` and 1 by `NUMNOTEQUAL`, the other one has 54 overall conditional jumps with just 1 `LT` and `PICKITEM` in all the other cases. So at a quick glance, it may be not worth the trouble, or maybe at least it requires better compiler support.

And `TRY`/`ENDTRY`. Well, if there is a question about exceptions support in VM count my vote against it, because IMO it makes VM more complicated for no good reason. It probably simplifies life of compiler developers, but that's exactly the case where I'd prefer to trade off compiler complexity for VM simplicity.

**Comment by igormcoelho** [comment]
So in the end you liked the TRY CATCH model @erikzhang 😂 I like ENDTRY name 👍 can we support a finally as well?

**Comment by erikzhang** [comment]
> So at a quick glance, it may be not worth the trouble, or maybe at least it requires better compiler support.

@lightszero Does the compiler need the conditional jump opcodes?
