### ISSUE TITLE
Why is Size of Integer(0) stack item 0?

### ISSUE THREAD

**Issue by ixje** [neo-project/neo-vm#289]
See title. Set in code here
https://github.com/neo-project/neo-vm/blob/5830d0e2d5e362801f4dfcb653e95d23f91267be/src/neo-vm/Types/Integer.cs#L22-L28

where `Size`is internally of type `BigInteger`. The way I see it an `Integer` stack item still has a size of 1, not zero. 
```C#
BigInteger b1 = new BigInteger(0);
Console.WriteLine($"{b1.IsZero} {b1.GetByteCount()}"); // True 1
```
Note that a Boolean stack item (which is also a `PrimitiveType`) always returns 1 for `Size`, including for a `false` value.  This leads me to believe an `Integer(0)` should also be 1 for `Size`, no? If not, why not?

The only instruction I see it used in thus far is in `OpCode.SIZE`; https://github.com/neo-project/neo-vm/blob/5830d0e2d5e362801f4dfcb653e95d23f91267be/src/neo-vm/ExecutionEngine.cs#L925-L927

**Comment by shargon** [comment]
The boolean behaviour was changed thanks to your advice https://github.com/neo-project/neo-vm/issues/129

According to Integer question, I can't remember well why we decide this ...

**Comment by ixje** [comment]
@shargon yeah I remember that discussion, and that's exactly why I'm confused as to why `Integer` now has similar behaviour as the old Boolean. That same argumentation still holds .

**Comment by erikzhang** [comment]
Integer's serialization follows the principle of least leading zeros.

**Comment by ixje** [comment]
😕 
What breaks or degrades integer does not follow that principle?

**Comment by igormcoelho** [comment]
Hi all, we had had this discussion before, and the idea is simple and efficient in two manners:
First: like @erikzhang said, all leading zeroes are removed, thus size is zero. Obviously, the actual "size" is the structure/object is greater than zero, it must have some internal C# counter, some pointers for methods, inheritance table, etc, etc, but we talk about the representational size of the NVM Integer object, which is zero, regardless of being implemented in Python, C++ or C#.
Second: we use to have Integer(0) serialized as 0x00 (not empty 0x''), but this had to be treated as an exception (since it was the only case that not every zero was stripped), and there's a HUGE advantage of treating Integer(0) as empty bytearray: it can be automatically garbage collected from blockchain storage (thus automatically allowing that every empty NEP-5 token account to be removed as soon as it reaches zero, even if contract designer forgot to write the Storage.Delete operation). On neo-project/neo we can also find such discussions, you can find on "garbage collection" issues or something like that.

**Comment by ixje** [comment]
Thanks for the link and some background info @igormcoelho 👍 
The link looks nice for helping people understand the `2.x` VM, but I'm currently only interested in the `3.x`, if there's ever going to be a `3.x` version I'll be sure to point people at it.
