### ISSUE TITLE
Create a better unittest for NEOVM

### ISSUE THREAD

**Issue by lightszero** [neo-project/neo-vm#295]
NeoVM's unittest is hard to use for now.

how about we use a ASM like string to define the NEF,
like 
```

{
    PUSH 1//push 1 number
    PUSH 2
    CALL method1
    RET;
}
method1:
{
label1：
    ADD
88:
    RET
}
```

**Comment by shargon** [comment]
It's good but this will be inside the json format (as script), or you have plans for other format?

**Comment by lightszero** [comment]
首先我们定义一个文本形式的汇编语言
因为定位为UnitTest中使用的脚本，我们就在这里讨论？还是要写一个标准
@erikzhang @shargon @Tommo-L 

一、这是一个例子

```c#
    PUSH 1//push 1 number
debugpoint1:
    PUSH 2
    CALL method1
    RET;
method1:
{
    ADD
    JMP ”88“
88:
    RET
}
```

二、使用方法
byte[] nef  = FromTestScript(asmstr);
在Unittest中封装一个这样的方法，实现转换过程，主要用于方便实现NEOMV的UnitTest

在执行时增加一个ExecuteToLabel的功能
比如ExecuteToLabel("debugpoint1");
可以直接让UnitTest执行到标签对应的地址，这样检查起来方便多了。

后续可以集成到json之类

三、脚本规则

1.允许   **//注释**   和**大括号{}**  和**封号;**，他们不产生任何作用，仅为了便于约定

2.只有两种行，指令行和标签行，指令行不允许换行书写，

3.标签 可是是数字与字符串下划线的组合，以 **冒号:** 结尾

4.所有指令都是OPCODE 加空格 加 参数的格式，无参数留空，参数
支持 数字 数组 字符串
比如
PUSHINT16 [0x02,0x55]
PUSHINT16 21762
PUSHINT16 "AA"

5.增加一条虚拟指令 PUSH，PUSH根据参数自动生成对应的指令
比如上边的PUSHINT16
直接用PUSH “AA"就可以

6.所有含有地址跳转的指令，都改为使用标签的名字做为参数，生成NEF时自动处理
比如,有多个地址的逗号隔开
JMP ”88“
CALL method01
TRY offsetcatch,offsetfinal

7.不需要写_L指令，比如JMP_L,生成NEF时自动处理

**Comment by shargon** [comment]
`PUSHINT16 [0x02,0x55]` it's the same as `PUSHINT16 0x0255` ?

The asm format that you define seems good, but it is not clear to me how you want to integrate it with the unit tests.

**Comment by lightszero** [comment]
same as PUSHINT16 0x5502
same as PUSHINT16 21762

first ,we could write c# unittest code for it

```c#
  string asm=@"
 xxx
x
xxx
abcd:
xx
xx
aaa:
 "
byte[] nef = FromTestScript(asmstr);
var addr = FrormTestScript(asmstr,"abcd");
TestEngine.ExecuteTo("abcd");
//add testcode
TestEngine.ExecuteTo("aaa");
//add testcode
```

and nextstep,we can add a unittest txt file for test,
```
[TESTSCRIPT]
 xxx
x
xxx
abcd:
xx
xx
aaa:

[TESTSTEP]
ExecuteTo:"abcd"
Assert:Evalstack.xxx=xxx
...
..

[TESTSTEP]
ExecuteTo:"aaa"
...
...
..
[TESTSTEP]
...
..
```

**Comment by shargon** [comment]
`ExecuteTo:"abcd"` i like it, "abcd" it's a label, right?

**Comment by lightszero** [comment]
yes

**Comment by Tommo-L** [comment]
I agree that we may need a more simply and clear script format.

**Comment by shargon** [comment]
What do you think about something like this:

```
{
    PUSH 1//push 1 number
    PUSH 2
    CALL method1
    RET;
}
method1:
{
label1：
    [Assert:CurrentContext.EvaluationStack.Count=1]
    [Assert:CurrentContext.EvaluationStack[0]={Integer:123}]
    ADD
88:
    RET
}
```

**Comment by ixje** [comment]
> What do you think about something like this:

It would be nice if the JSON tests actually remains usable for other implementations as well. The above (specifically):
> Assert:CurrentContext.EvaluationStack[0].Count

Seems to be a direct mapping to the C# implementation which form a portability standpoint is bad.


I like some of the suggestions by @lightszero 
1. Instructions format `<OpCode> <Parameters>` 👍 . Allowing non-json standard features like comments (//) 👎 (breaks some strict JSON parsers) , allowing inconsistent instruction naming (=case-insensitive) and inconsistent parameter descriptions (= e.g. appending or not appending "0x" to bytearrays) 👎 
2. Not a big fan of the virtual instruction. I believe tests should be explicit instead of implicit which this feature creates.
3. `ExecuteToLabel ("debugpoint1");` Good idea. There might be some things lost in Google translate, but how about adding a `breakPoints` key to the `step` instead? e.g.
```
 "steps": [
    {
        "breakPoints": 
        {
            "add": [123, 111], // array of IP location
            "remove": []
        },
        "actions": [
            "execute"
        ],
        "result": {
        ...
        }
    }
    { /* step 2 */}
]
```
That should be able to get the same results no? 

I could not follow the translation of the JMP(_L) instructions 🤷‍♂
