### ISSUE TITLE
[Question] How to execute a contract bytecode directly with NeoVM?

### ISSUE THREAD

**Issue by fCorleone** [neo-project/neo-vm#341]
I'm new to Neo blockchain, I would like to test my contract directly with the virtual machine, is there any way to do that?

**Comment by Tommo-L** [comment]
If just want to have a test, can use the following code:

```cs
ExecutionEngine engine = new ExecutionEngine();
byte[] contractScript = new byte[] { 0x10 }; // set contract script
engine.LoadScript(contractScript);
engine.Execute(); // engine.
Console.WriteLine(engine.State);
```
At the same time, you can also expand the `ExecutionEngine`, like https://github.com/neo-project/neo/blob/master/src/neo/SmartContract/ApplicationEngine.cs#L48

**Comment by dns7030** [comment]
@fCorleone Hi, welcome to Neo blockchain ecosystem and thank you for your interest! Are you on Discord as well? I'd love to learn about your project and see how we at Neo Global Development can promote it.

> that

**Comment by ixje** [comment]
@fCorleone Be aware that this `neo-vm` project alone is not sufficient to test full fledged smart contracts. The reason being is that it does not include the interoperability layer for doing things like; 
- persisting data to storage, retrieving data from storage
- serialising data
- reading block/transaction data
- validating smart contract invokers etc (for more functionality see [the API](https://docs.neo.org/v3/docs/en-us/reference/scapi/api/System.html))

If you want to have the "full" support, then you'd have to use the [ApplicationEngine](https://github.com/neo-project/neo/blob/master/src/neo/SmartContract/ApplicationEngine.cs#L17) instead of `ExecutionEngine`. `ExecutionEngine` is the bare bones VM, `ApplicationEngine` adds the interoperability support. 

Without knowing why you want to test your contract directly against the VM it is hard to give the right instructions. If you just want to test your smart contract without having to request test GAS and such, then I'd suggest having a look at https://marketplace.visualstudio.com/items?itemName=ngd-seattle.neo-blockchain-toolkit

**Comment by doubiliu** [comment]
@fCorleone Maybe he is just want to deploy and test his contract without starting a node.
```
            StoreView snapshot = initsnapshot.Clone();
            string manifestString = ""  ; //Read it from your manifest file and convert it to hexstring";
            var manifest = ContractManifest.Parse(manifestString.HexToBytes());
            var nefFileString = "";//Read it from your nel file and convert it to hexstring";
            NefFile file = new NefFile();
            file.Deserialize(new BinaryReader(new MemoryStream(nefFileString.HexToBytes())));
            ContractState contract = new ContractState
            {
                Id = snapshot.ContractId.GetAndChange().NextId++,
                Script = file.Script,
                Manifest = manifest
            };
            snapshot.Contracts.Add(file.ScriptHash, contract);
            
            ScriptBuilder sb = new ScriptBuilder();
            sb.EmitAppCall(file.ScriptHash, "method",......);

            var engine = ApplicationEngine.Run(sb.ToArray(), snapshot, null, testMode: true);
            if (engine.State != VMState.HALT) throw new ApplicationException();
```

**Comment by fCorleone** [comment]
Thank you all for the suggestions. I think @doubiliu and @Tommo-L's answers have solved my issue. Thanks again.
