### ISSUE TITLE
**OOM** in OpCode `POW`

### ISSUE THREAD

**Issue by vang1ong7ang** [neo-project/neo-vm#425]
```
1201fe00a34a9d9e12001ba3a3
```

source code: <https://github.com/lazynode/Tanya/pull/10>

Essentially becasue `BigInteger.Pow(value, exponent)` mallocs a lot of mem. See:

https://github.com/neo-project/neo-vm/blob/5da8f71782812d9aa298c819c429e314f37938ab/src/neo-vm/ExecutionEngine.cs#L846-L852

**Comment by dusmart** [comment]
> BTW, IMO **MODPOW** which introduced by @igormcoelho here #77 could be more useful than **POW**.

When I try to implement some hash function on chain. I found that `MODPOW` is really useful than `POW`. And `MODMUL` is useful than `MUL` for me.

In v3.1.0, I cannot even do the `uint256 * uint256` calculation because the result will exceed the max size of `Integer`. I have to use lots of GAS to bypass the multiplication.
